spring:
  config:
    activate:
      on-profile: qa

build:
  version: "2.0.0"

loans:
  message: "Welcome to the Loans Service Using Qa"
  contactDetails:
    name: "John Doe-Developer(QA)"
    email: "sanjiv@gmail.com"
  onCallSupport:
    - "9932938627"
    - "7787878787"